#ifndef DISTRHO_PLUGIN_INFO_H
#define DISTRHO_PLUGIN_INFO_H

#define DISTRHO_PLUGIN_BRAND "GodotDistrho"
#define DISTRHO_PLUGIN_NAME "GodotDistrho"
#define DISTRHO_PLUGIN_URI "https://github.com/nonameentername/godot-distrho"
#define DISTRHO_PLUGIN_CLAP_ID "GodotDistrho"

// #define DISTRHO_UI_USE_CUSTOM          1
// #define DISTRHO_UI_CUSTOM_INCLUDE_PATH "godot_gui_widget.h"
// #define DISTRHO_UI_CUSTOM_WIDGET_TYPE  DGL_NAMESPACE::GodotDistrhoGuiWidget

#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_HAS_EMBED_UI 0
#define DISTRHO_PLUGIN_HAS_EXTERNAL_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_WANT_PROGRAMS 0
#define DISTRHO_PLUGIN_WANT_STATE 0
#define DISTRHO_UI_FILE_BROWSER 0
#define DISTRHO_UI_USE_NANOVG 0

#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 1
#define DISTRHO_UI_USER_RESIZABLE 0

#define DISTRHO_PLUGIN_EXTRA_IO {2, 2},

#define DISTRHO_PLUGIN_CLAP_FEATURES "audio-effect", "multi-effects", "mono"
#define DISTRHO_PLUGIN_LV2_CATEGORY "lv2:SimulatorPlugin"
#define DISTRHO_PLUGIN_VST3_CATEGORIES "Fx|Dynamics|Mono"

#define DISTRHO_PLUGIN_BRAND_ID GDot
#define DISTRHO_PLUGIN_UNIQUE_ID GDot

#define DISTRHO_UI_DEFAULT_WIDTH 940
#define DISTRHO_UI_DEFAULT_HEIGHT 398

#endif
